name = "SampleProject"
uuid = "a0e5de12-d1c1-11e9-0d35-b5e717783b63"
authors = ["Max Bennedich <bennedich@gmail.com>"]
version = "0.1.0"

[deps]
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
